version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AUTH_SECRET=*
      - AUTH0_CLIENT_ID=*
      - AUTH0_CLIENT_SECRET=*
      - AUTH0_ISSUER=*
      - NEXT_AUTH_URL=http://localhost:3000
      - POSTGRES_URL=postgresql://postgres:*@postgres:5432/chatbot2
      - GOOGLE_CLIENT_ID=*
      - GOOGLE_CLIENT_SECRET=*
      - MINIO_ENDPOINT=*
      - MINIO_ACCESS_KEY=*
      - MINIO_SECRET_KEY=*
      - MINIO_PORT=80
      - AUTH_TRUST_HOST=http://localhost:3000
      - INIT_ADMIN_USER_EMAIL=*
      - LANGFUSE_SECRET_KEY=*
      - LANGFUSE_PUBLIC_KEY=*
      - LANGFUSE_HOST=https://cloud.langfuse.com
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=*
      - POSTGRES_DB=chatbot2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
